// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjl1LNTlTYdpGOdTLRX2HvX9lPC-0rcYM',
    appId: '1:267790944430:web:7a9573c1eb4703dc9a453f',
    messagingSenderId: '267790944430',
    projectId: 'saarthi-931dd',
    authDomain: 'saarthi-931dd.firebaseapp.com',
    storageBucket: 'saarthi-931dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtzk_I1315eF_C4ypsJUYkQot9Hjg4-g',
    appId: '1:267790944430:android:7cbc7c7dad49a1c29a453f',
    messagingSenderId: '267790944430',
    projectId: 'saarthi-931dd',
    storageBucket: 'saarthi-931dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzRMK9di-9Tp1OetNXmB9M25wBmtOZvw',
    appId: '1:267790944430:ios:a4974141b3a157ed9a453f',
    messagingSenderId: '267790944430',
    projectId: 'saarthi-931dd',
    storageBucket: 'saarthi-931dd.firebasestorage.app',
    iosBundleId: 'com.example.saarthi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzRMK9di-9Tp1OetNXmB9M25wBmtOZvw',
    appId: '1:267790944430:ios:a4974141b3a157ed9a453f',
    messagingSenderId: '267790944430',
    projectId: 'saarthi-931dd',
    storageBucket: 'saarthi-931dd.firebasestorage.app',
    iosBundleId: 'com.example.saarthi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjl1LNTlTYdpGOdTLRX2HvX9lPC-0rcYM',
    appId: '1:267790944430:web:c8206aa8010e8e829a453f',
    messagingSenderId: '267790944430',
    projectId: 'saarthi-931dd',
    authDomain: 'saarthi-931dd.firebaseapp.com',
    storageBucket: 'saarthi-931dd.firebasestorage.app',
  );
}
